## options: -ignore_missing -ignore_src_filter_spec_err -top pcounter_veloce -type hdl -task sim -spec_path /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter -spec_path /usr/local/projects/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl -spec_path /usr/local/projects/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b -tool modelsim -mode hier -prefix dut -block pcounter_veloce -output_dir /usr2/xiaoshao/uvm_training_labs/lab11/lab1/unmanaged/qvmr/xiaoshao/libs/default/hdl/modelsim/6.6g/LINUX64 -default_work hdl_work -gen_output 1
$(call __include_trace)
################################################################################
#
# Makefile auto-generated by QBAR
#
################################################################################


################################################################################
#
# Variable Definitions
#
################################################################################

QDISTILLER_PATH?=/pkg/qvmr/2.10.2/qbar/qdistiller_default
QC_OPTS?=
__DUT_QAFENE_DEPS[xl_vip_hdl] += ${__DUT_QAFENE_REQUIRES[xl_vip_hdl]}
__DUT_SPEC_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/compile.xml
__DUT_FILELISTS[xl_vip_hdl] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/unmanaged/qvmr/xiaoshao/libs/default/hdl/modelsim/6.6g/LINUX64/xl_vip_hdl_hier_dut_sv.f
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlRngTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlVeraSystemClock.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlClockAdvancer.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlResetGenerator.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlMemoryTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlEdgeDetector.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/SoftCores/AxiSlaveCore/vsms5505.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/SoftCores/AxiSlaveCore/vsmu5505.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlGpioTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiSlaveTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiR0p0MasterTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiR0p0SlaveTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiMasterTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAhbMasterTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAhbSlaveTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAhbMonitor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlRngTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlVeraSystemClock.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlClockAdvancer.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlResetGenerator.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlMemoryTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlEdgeDetector.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/SoftCores/AxiSlaveCore/vsms5505.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/SoftCores/AxiSlaveCore/vsmu5505.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/XlGpioTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiSlaveTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiR0p0MasterTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiR0p0SlaveTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAxiMasterTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAhbMasterTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAhbSlaveTransactor.sv
__DUT_SOURCE_FILES[xl_vip_hdl][1] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/../../xl_vip/lib/hdl_veloce/XlAhbMonitor.sv
__DUT_FILELISTS[xl_vip_hdl][1] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/unmanaged/qvmr/xiaoshao/libs/default/hdl/modelsim/6.6g/LINUX64/xl_vip_hdl_hier_dut_sv.f
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${__DUT_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += $${DUT_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${DUT_DEPS_}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${XL_VIP_HDL_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += $${XL_VIP_HDL_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${XL_VIP_HDL_DEPS_}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${__DUT_SOURCE_FILES[xl_vip_hdl][1]}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${__DUT_OPTS_FILES[xl_vip_hdl]}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__DUT_FILELISTS[xl_vip_hdl][1]}),)
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${__DUT_QAFENE_REQUIRES[xl_vip_hdl]}
__DUT_QAFENE_DEPS[xl_vip_hdl][1] += ${__DUT_CHECK_FILES[xl_vip_hdl]}
__DUT_QAFENE_OOPS[xl_vip_hdl][1] += ${__DUT_INIT}
__DUT_QAFENE_OOPS[xl_vip_hdl][1] += ${__DUT_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl][1] += $${DUT_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl][1] += ${DUT_OOPS_}
__DUT_QAFENE_OOPS[xl_vip_hdl][1] += ${XL_VIP_HDL_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl][1] += $${XL_VIP_HDL_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl][1] += ${XL_VIP_HDL_OOPS_}
__HDL_QAFENE_TARGET[xl_vip_hdl][1] = ${__DUT_TOUCH_FILE_DIR}/qbar_block^xl_vip_hdl.1
__DUT_QAFENE_DEPS[xl_vip_hdl] += ${__DUT_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl] += $${DUT_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl] += ${DUT_DEPS_}
__DUT_QAFENE_DEPS[xl_vip_hdl] += ${XL_VIP_HDL_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl] += $${XL_VIP_HDL_DEPS}
__DUT_QAFENE_DEPS[xl_vip_hdl] += ${XL_VIP_HDL_DEPS_}
__DUT_QAFENE_DEPS[xl_vip_hdl] += ${__HDL_QAFENE_TARGET[xl_vip_hdl][1]}
__DUT_QAFENE_OOPS[xl_vip_hdl] += ${__DUT_INIT}
__DUT_QAFENE_OOPS[xl_vip_hdl] += ${__DUT_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl] += $${DUT_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl] += ${DUT_OOPS_}
__DUT_QAFENE_OOPS[xl_vip_hdl] += ${XL_VIP_HDL_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl] += $${XL_VIP_HDL_OOPS}
__DUT_QAFENE_OOPS[xl_vip_hdl] += ${XL_VIP_HDL_OOPS_}
__HDL_QAFENE_TARGET[xl_vip_hdl] = ${__DUT_TOUCH_FILE_DIR}/qbar_block^xl_vip_hdl
__DUT_QAFENE_TARGET[xl_vip_hdl] = ${__HDL_QAFENE_TARGET[xl_vip_hdl]}
__DUT_QAFENE_REQUIRES[pcounter_veloce] += ${__HDL_QAFENE_TARGET[xl_vip_hdl]${__DUT_IGNORE_DEPS}}
__DUT_QAFENE_DEPS[pcounter_veloce] += ${__DUT_QAFENE_REQUIRES[pcounter_veloce]}
__DUT_SPEC_FILES[pcounter_veloce] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/compile.xml
__DUT_FILELISTS[pcounter_veloce] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/unmanaged/qvmr/xiaoshao/libs/default/hdl/modelsim/6.6g/LINUX64/pcounter_veloce_hier_dut_sv.f
__DUT_SOURCE_FILES[pcounter_veloce] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/pcounter.sv
__DUT_SOURCE_FILES[pcounter_veloce] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/pcounter_wrapper.sv
__DUT_SOURCE_FILES[pcounter_veloce] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/test_bench.sv
__DUT_SOURCE_FILES[pcounter_veloce] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/clock_bfm.sv
__DUT_SOURCE_FILES[pcounter_veloce][1] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/pcounter.sv
__DUT_SOURCE_FILES[pcounter_veloce][1] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/pcounter_wrapper.sv
__DUT_SOURCE_FILES[pcounter_veloce][1] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/test_bench.sv
__DUT_SOURCE_FILES[pcounter_veloce][1] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/clock_bfm.sv
__DUT_FILELISTS[pcounter_veloce][1] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/unmanaged/qvmr/xiaoshao/libs/default/hdl/modelsim/6.6g/LINUX64/pcounter_veloce_hier_dut_sv.f
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${__DUT_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += $${DUT_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${DUT_DEPS_}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${PCOUNTER_VELOCE_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += $${PCOUNTER_VELOCE_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${PCOUNTER_VELOCE_DEPS_}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${__DUT_SOURCE_FILES[pcounter_veloce][1]}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${__DUT_OPTS_FILES[pcounter_veloce]}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__DUT_FILELISTS[pcounter_veloce][1]}),)
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${__DUT_QAFENE_REQUIRES[pcounter_veloce]}
__DUT_QAFENE_DEPS[pcounter_veloce][1] += ${__DUT_CHECK_FILES[pcounter_veloce]}
__DUT_QAFENE_OOPS[pcounter_veloce][1] += ${__DUT_INIT}
__DUT_QAFENE_OOPS[pcounter_veloce][1] += ${__DUT_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce][1] += $${DUT_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce][1] += ${DUT_OOPS_}
__DUT_QAFENE_OOPS[pcounter_veloce][1] += ${PCOUNTER_VELOCE_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce][1] += $${PCOUNTER_VELOCE_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce][1] += ${PCOUNTER_VELOCE_OOPS_}
__HDL_QAFENE_TARGET[pcounter_veloce][1] = ${__DUT_TOUCH_FILE_DIR}/qbar_block^pcounter_veloce.1
__DUT_QAFENE_DEPS[pcounter_veloce] += ${__DUT_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce] += $${DUT_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce] += ${DUT_DEPS_}
__DUT_QAFENE_DEPS[pcounter_veloce] += ${PCOUNTER_VELOCE_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce] += $${PCOUNTER_VELOCE_DEPS}
__DUT_QAFENE_DEPS[pcounter_veloce] += ${PCOUNTER_VELOCE_DEPS_}
__DUT_QAFENE_DEPS[pcounter_veloce] += ${__HDL_QAFENE_TARGET[pcounter_veloce][1]}
__DUT_QAFENE_OOPS[pcounter_veloce] += ${__DUT_INIT}
__DUT_QAFENE_OOPS[pcounter_veloce] += ${__DUT_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce] += $${DUT_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce] += ${DUT_OOPS_}
__DUT_QAFENE_OOPS[pcounter_veloce] += ${PCOUNTER_VELOCE_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce] += $${PCOUNTER_VELOCE_OOPS}
__DUT_QAFENE_OOPS[pcounter_veloce] += ${PCOUNTER_VELOCE_OOPS_}
__HDL_QAFENE_TARGET[pcounter_veloce] = ${__DUT_TOUCH_FILE_DIR}/qbar_block^pcounter_veloce
__DUT_QAFENE_TARGET[pcounter_veloce] = ${__HDL_QAFENE_TARGET[pcounter_veloce]}
__DUT_MK_INCLUDED = ${true}
DUT_DEPS?=
DUT_DEPS_?=
__DUT_LIBS += hdl_work:${__DUT_BIN_DIR}/hdl_work
__DUT_LIB_NAMES += hdl_work
__DUT_LIB_PATHS += ${__DUT_BIN_DIR}/hdl_work
__DUT_VLOG_LIB_NAMES += hdl_work
__SC_LIB_NAMES += 
__DUT_SPEC_FILES[pcounter_veloce] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hdl/compile.xml
__DUT_SPEC_FILES[pcounter_veloce] += /usr2/xiaoshao/uvm_training_labs/lab11/lab1/pcounter/src/compile.xml
__DUT_SPEC_FILES += ${__DUT_SPEC_FILES[pcounter_veloce]}
__SELF = /usr2/xiaoshao/uvm_training_labs/lab11/lab1/unmanaged/qvmr/xiaoshao/libs/default/hdl/modelsim/6.6g/LINUX64/pcounter_veloce_hier_dut.mk

.PHONY: xl_vip_hdl pcounter_veloce

################################################################################
#
# Command Definitions
#
################################################################################

ifneq (${DUT_DONE},1)
ifeq (${__QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[xl_vip_hdl][1]}]},)

.SECONDEXPANSION:
${__HDL_QAFENE_TARGET[xl_vip_hdl][1]} : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
${__HDL_QAFENE_TARGET[xl_vip_hdl][1]} : \
	${__DUT_QAFENE_DEPS[xl_vip_hdl][1]} | \
	${__DUT_QAFENE_OOPS[xl_vip_hdl][1]}
	$(call __open_task,Compiling xl_vip_hdl for modelsim 1/1 (dut block 1 of 2),${__DUT_INFO})
	-@$(call __quiet_rm,${__DUT_FILELISTS[xl_vip_hdl][1]}.recompile,${__DUT_LOG})
	$(call __locked_exec, \
	  ${__DUT_BIN_DIR}/hdl_work, \
	  ${CD} ${__DUT_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__DUT_VLOG_OPTS} ${DUT_VLOG_OPTS} ${DUT_VLOG_OPTS_} ${__XL_VIP_HDL_VLOG_OPTS} ${XL_VIP_HDL_VLOG_OPTS} ${XL_VIP_HDL_VLOG_OPTS_} \
	    ${__DUT_SV_VLOG_OPTS} ${DUT_SV_VLOG_OPTS} ${DUT_SV_VLOG_OPTS_} ${__XL_VIP_HDL_SV_VLOG_OPTS} ${XL_VIP_HDL_SV_VLOG_OPTS} ${XL_VIP_HDL_SV_VLOG_OPTS_} \
	     \
	    +define+TBX_MODE \
	    +define+TBX_WORKAROUND \
	    +define+TBX_XL_SIM_MODE \
	    -f `if [ -e ${__DUT_BIN_DIR}/./xl_vip_hdl_hier_dut_sv.f.recompile ]; then echo ./xl_vip_hdl_hier_dut_sv.f.recompile; else echo ./xl_vip_hdl_hier_dut_sv.f; fi` \
	    -work hdl_work \
	    ${__OVERRIDE_XL_VIP_HDL_VLOG_OPTS} ${__XL_VIP_HDL_VLOG_CMD_TRAIL} ${__XL_VIP_HDL_VLOG_SV_CMD_TRAIL}, \
	  ${__DUT_LOG}, \
	)
	$(call __dummy,$@,${__DUT_LOG})
	$(call __close_task,${__DUT_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[xl_vip_hdl][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[xl_vip_hdl]}]},)

.SECONDEXPANSION:
${__HDL_QAFENE_TARGET[xl_vip_hdl]} : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
${__HDL_QAFENE_TARGET[xl_vip_hdl]} : \
	${__DUT_QAFENE_DEPS[xl_vip_hdl]} | \
	${__DUT_QAFENE_OOPS[xl_vip_hdl]}
	$(call __dummy,$@,${__DUT_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[xl_vip_hdl]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[xl_vip_hdl]},)

.SECONDEXPANSION:
xl_vip_hdl : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
xl_vip_hdl : \
	${__HDL_QAFENE_TARGET[xl_vip_hdl]} | 

$(eval __QAFENE_TARGET_DEFINED[xl_vip_hdl] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.xl_vip_hdl]},)

.SECONDEXPANSION:
clean_block.xl_vip_hdl : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
clean_block.xl_vip_hdl :  | 
	$(call __open_task,Cleaning xl_vip_hdl for modelsim,${__DUT_INFO})
	@$(call __quiet_rm, ${__HDL_QAFENE_TARGET[xl_vip_hdl]},)
	$(call __close_task,${__DUT_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.xl_vip_hdl] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[pcounter_veloce][1]}]},)

.SECONDEXPANSION:
${__HDL_QAFENE_TARGET[pcounter_veloce][1]} : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
${__HDL_QAFENE_TARGET[pcounter_veloce][1]} : \
	${__DUT_QAFENE_DEPS[pcounter_veloce][1]} | \
	${__DUT_QAFENE_OOPS[pcounter_veloce][1]}
	$(call __open_task,Compiling pcounter_veloce for modelsim 1/1 (dut block 2 of 2),${__DUT_INFO})
	-@$(call __quiet_rm,${__DUT_FILELISTS[pcounter_veloce][1]}.recompile,${__DUT_LOG})
	$(call __locked_exec, \
	  ${__DUT_BIN_DIR}/hdl_work, \
	  ${CD} ${__DUT_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__DUT_VLOG_OPTS} ${DUT_VLOG_OPTS} ${DUT_VLOG_OPTS_} ${__PCOUNTER_VELOCE_VLOG_OPTS} ${PCOUNTER_VELOCE_VLOG_OPTS} ${PCOUNTER_VELOCE_VLOG_OPTS_} \
	    ${__DUT_SV_VLOG_OPTS} ${DUT_SV_VLOG_OPTS} ${DUT_SV_VLOG_OPTS_} ${__PCOUNTER_VELOCE_SV_VLOG_OPTS} ${PCOUNTER_VELOCE_SV_VLOG_OPTS} ${PCOUNTER_VELOCE_SV_VLOG_OPTS_} \
	     \
	     \
	    -f `if [ -e ${__DUT_BIN_DIR}/./pcounter_veloce_hier_dut_sv.f.recompile ]; then echo ./pcounter_veloce_hier_dut_sv.f.recompile; else echo ./pcounter_veloce_hier_dut_sv.f; fi` \
	    -work hdl_work \
	    ${__OVERRIDE_PCOUNTER_VELOCE_VLOG_OPTS} ${__PCOUNTER_VELOCE_VLOG_CMD_TRAIL} ${__PCOUNTER_VELOCE_VLOG_SV_CMD_TRAIL}, \
	  ${__DUT_LOG}, \
	)
	$(call __dummy,$@,${__DUT_LOG})
	$(call __close_task,${__DUT_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[pcounter_veloce][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[pcounter_veloce]}]},)

.SECONDEXPANSION:
${__HDL_QAFENE_TARGET[pcounter_veloce]} : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
${__HDL_QAFENE_TARGET[pcounter_veloce]} : \
	${__DUT_QAFENE_DEPS[pcounter_veloce]} | \
	${__DUT_QAFENE_OOPS[pcounter_veloce]}
	$(call __dummy,$@,${__DUT_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HDL_QAFENE_TARGET[pcounter_veloce]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[pcounter_veloce]},)

.SECONDEXPANSION:
pcounter_veloce : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
pcounter_veloce : \
	${__HDL_QAFENE_TARGET[pcounter_veloce]} | 

$(eval __QAFENE_TARGET_DEFINED[pcounter_veloce] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.pcounter_veloce]},)

.SECONDEXPANSION:
clean_block.pcounter_veloce : __CURRENT_LOG_FILE=${__DUT_LOG_FILE}
clean_block.pcounter_veloce :  | 
	$(call __open_task,Cleaning pcounter_veloce for modelsim,${__DUT_INFO})
	@$(call __quiet_rm, ${__HDL_QAFENE_TARGET[pcounter_veloce]},)
	$(call __close_task,${__DUT_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.pcounter_veloce] := ${true})

endif
endif

