## options: -ignore_missing -ignore_src_filter_spec_err -type hvl -task sim -top uvc_pcounter_tb -tool modelsim -mode hier -disable_global_libs -spec_path /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm -spec_path /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif -spec_path /usr/local/projects/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b -disable_global_libs -phony -prefix tb -block uvc_pcounter_tb -output_dir /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64 -default_work tb_work -gen_output 1
$(call __include_trace)
################################################################################
#
# Makefile auto-generated by QBAR
#
################################################################################


################################################################################
#
# Variable Definitions
#
################################################################################

QDISTILLER_PATH?=/pkg/qvmr/2.10.2/qbar/qdistiller_default
QC_OPTS?=
__TB_QAFENE_DEPS[uvm] += ${__TB_QAFENE_REQUIRES[uvm]}
__TB_SPEC_FILES[uvm] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/compile.xml
__TB_FILELISTS[uvm] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvm_hier_tb_sv.f
__TB_SOURCE_FILES[uvm] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/uvm_pkg.sv
__TB_DPI_C_FILES += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/dpi/uvm_dpi.cc
__TB_SOURCE_FILES[uvm] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/dpi/uvm_dpi.cc
__TB_SOURCE_FILES[uvm] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/uvm_macros.svh
__TB_CHECK_FILES[uvm] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/uvm_macros.svh
__TB_SOURCE_FILES[uvm][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/uvm_pkg.sv
__TB_FILELISTS[uvm][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvm_hier_tb_sv.f
__TB_QAFENE_DEPS[uvm][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvm][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvm][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvm][1] += ${UVM_DEPS}
__TB_QAFENE_DEPS[uvm][1] += $${UVM_DEPS}
__TB_QAFENE_DEPS[uvm][1] += ${UVM_DEPS_}
__TB_QAFENE_DEPS[uvm][1] += ${__TB_SOURCE_FILES[uvm][1]}
__TB_QAFENE_DEPS[uvm][1] += ${__TB_OPTS_FILES[uvm]}
__TB_QAFENE_DEPS[uvm][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[uvm][1]}),)
__TB_QAFENE_DEPS[uvm][1] += ${__TB_QAFENE_REQUIRES[uvm]}
__TB_QAFENE_DEPS[uvm][1] += ${__TB_CHECK_FILES[uvm]}
__TB_QAFENE_OOPS[uvm][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvm][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvm][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvm][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvm][1] += ${UVM_OOPS}
__TB_QAFENE_OOPS[uvm][1] += $${UVM_OOPS}
__TB_QAFENE_OOPS[uvm][1] += ${UVM_OOPS_}
__HVL_QAFENE_TARGET[uvm][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvm.1
__TB_QAFENE_DEPS[uvm] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvm] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvm] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvm] += ${UVM_DEPS}
__TB_QAFENE_DEPS[uvm] += $${UVM_DEPS}
__TB_QAFENE_DEPS[uvm] += ${UVM_DEPS_}
__TB_QAFENE_DEPS[uvm] += ${__HVL_QAFENE_TARGET[uvm][1]}
__TB_QAFENE_OOPS[uvm] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvm] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvm] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvm] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvm] += ${UVM_OOPS}
__TB_QAFENE_OOPS[uvm] += $${UVM_OOPS}
__TB_QAFENE_OOPS[uvm] += ${UVM_OOPS_}
__HVL_QAFENE_TARGET[uvm] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvm
__TB_QAFENE_TARGET[uvm] = ${__HVL_QAFENE_TARGET[uvm]}
__TB_QAFENE_REQUIRES[quvm_addons] += ${__HVL_QAFENE_TARGET[uvm]${__TB_IGNORE_DEPS}}
__TB_QAFENE_DEPS[quvm_addons] += ${__TB_QAFENE_REQUIRES[quvm_addons]}
__TB_SPEC_FILES[quvm_addons] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/compile.xml
__TB_FILELISTS[quvm_addons] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/quvm_addons_hier_tb_sv.f
__TB_SOURCE_FILES[quvm_addons] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/quvm_addons_pkg.sv
__TB_SOURCE_FILES[quvm_addons][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/quvm_addons_pkg.sv
__TB_FILELISTS[quvm_addons][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/quvm_addons_hier_tb_sv.f
__TB_QAFENE_DEPS[quvm_addons][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[quvm_addons][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[quvm_addons][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[quvm_addons][1] += ${QUVM_ADDONS_DEPS}
__TB_QAFENE_DEPS[quvm_addons][1] += $${QUVM_ADDONS_DEPS}
__TB_QAFENE_DEPS[quvm_addons][1] += ${QUVM_ADDONS_DEPS_}
__TB_QAFENE_DEPS[quvm_addons][1] += ${__TB_SOURCE_FILES[quvm_addons][1]}
__TB_QAFENE_DEPS[quvm_addons][1] += ${__TB_OPTS_FILES[quvm_addons]}
__TB_QAFENE_DEPS[quvm_addons][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[quvm_addons][1]}),)
__TB_QAFENE_DEPS[quvm_addons][1] += ${__TB_QAFENE_REQUIRES[quvm_addons]}
__TB_QAFENE_DEPS[quvm_addons][1] += ${__TB_CHECK_FILES[quvm_addons]}
__TB_QAFENE_OOPS[quvm_addons][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[quvm_addons][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[quvm_addons][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[quvm_addons][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[quvm_addons][1] += ${QUVM_ADDONS_OOPS}
__TB_QAFENE_OOPS[quvm_addons][1] += $${QUVM_ADDONS_OOPS}
__TB_QAFENE_OOPS[quvm_addons][1] += ${QUVM_ADDONS_OOPS_}
__HVL_QAFENE_TARGET[quvm_addons][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^quvm_addons.1
__TB_QAFENE_DEPS[quvm_addons] += ${__TB_DEPS}
__TB_QAFENE_DEPS[quvm_addons] += $${TB_DEPS}
__TB_QAFENE_DEPS[quvm_addons] += ${TB_DEPS_}
__TB_QAFENE_DEPS[quvm_addons] += ${QUVM_ADDONS_DEPS}
__TB_QAFENE_DEPS[quvm_addons] += $${QUVM_ADDONS_DEPS}
__TB_QAFENE_DEPS[quvm_addons] += ${QUVM_ADDONS_DEPS_}
__TB_QAFENE_DEPS[quvm_addons] += ${__HVL_QAFENE_TARGET[quvm_addons][1]}
__TB_QAFENE_OOPS[quvm_addons] += ${__TB_INIT}
__TB_QAFENE_OOPS[quvm_addons] += ${__TB_OOPS}
__TB_QAFENE_OOPS[quvm_addons] += $${TB_OOPS}
__TB_QAFENE_OOPS[quvm_addons] += ${TB_OOPS_}
__TB_QAFENE_OOPS[quvm_addons] += ${QUVM_ADDONS_OOPS}
__TB_QAFENE_OOPS[quvm_addons] += $${QUVM_ADDONS_OOPS}
__TB_QAFENE_OOPS[quvm_addons] += ${QUVM_ADDONS_OOPS_}
__HVL_QAFENE_TARGET[quvm_addons] = ${__TB_TOUCH_FILE_DIR}/qbar_block^quvm_addons
__TB_QAFENE_TARGET[quvm_addons] = ${__HVL_QAFENE_TARGET[quvm_addons]}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += ${__TB_QAFENE_REQUIRES[xl_vip_hvl_sysv_open_kit]}
__TB_SPEC_FILES[xl_vip_hvl_sysv_open_kit] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hvl/sysv/compile_open_kit.xml
__TB_FILELISTS[xl_vip_hvl_sysv_open_kit] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/xl_vip_hvl_sysv_open_kit_hier_tb_sv.f
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${TBX_HOME}/questa/hdl/tbxEventPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${TBX_HOME}/questa/hdl/xtlm/xtlm_base_pkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${TBX_HOME}/questa/hdl/xtlm/xtlm_pkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HOME}/xl_vip/lib/XlSvPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HOME}/xl_vip/lib/XlSvTimeAdvancerPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HOME}/xl_vip/lib/XlSvResetGeneratorPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HOME}/xl_vip/lib/XlSvMemoryTransactorPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HOME}/xl_vip/lib/XlSvGpioTransactorPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HOME}/xl_vip/lib/XlSvEdgeDetectorPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${TBX_HOME}/questa/hdl/tbxEventPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${TBX_HOME}/questa/hdl/xtlm/xtlm_base_pkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${TBX_HOME}/questa/hdl/xtlm/xtlm_pkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HOME}/xl_vip/lib/XlSvPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HOME}/xl_vip/lib/XlSvTimeAdvancerPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HOME}/xl_vip/lib/XlSvResetGeneratorPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HOME}/xl_vip/lib/XlSvMemoryTransactorPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HOME}/xl_vip/lib/XlSvGpioTransactorPkg.sv
__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HOME}/xl_vip/lib/XlSvEdgeDetectorPkg.sv
__TB_FILELISTS[xl_vip_hvl_sysv_open_kit][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/xl_vip_hvl_sysv_open_kit_hier_tb_sv.f
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HVL_SYSV_OPEN_KIT_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += $${XL_VIP_HVL_SYSV_OPEN_KIT_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HVL_SYSV_OPEN_KIT_DEPS_}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${__TB_SOURCE_FILES[xl_vip_hvl_sysv_open_kit][1]}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${__TB_OPTS_FILES[xl_vip_hvl_sysv_open_kit]}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[xl_vip_hvl_sysv_open_kit][1]}),)
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${__TB_QAFENE_REQUIRES[xl_vip_hvl_sysv_open_kit]}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1] += ${__TB_CHECK_FILES[xl_vip_hvl_sysv_open_kit]}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HVL_SYSV_OPEN_KIT_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1] += $${XL_VIP_HVL_SYSV_OPEN_KIT_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1] += ${XL_VIP_HVL_SYSV_OPEN_KIT_OOPS_}
__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^xl_vip_hvl_sysv_open_kit.1
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += ${__TB_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += $${TB_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += ${TB_DEPS_}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HVL_SYSV_OPEN_KIT_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += $${XL_VIP_HVL_SYSV_OPEN_KIT_DEPS}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HVL_SYSV_OPEN_KIT_DEPS_}
__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit] += ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit][1]}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit] += ${__TB_INIT}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit] += ${__TB_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit] += $${TB_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit] += ${TB_OOPS_}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HVL_SYSV_OPEN_KIT_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit] += $${XL_VIP_HVL_SYSV_OPEN_KIT_OOPS}
__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit] += ${XL_VIP_HVL_SYSV_OPEN_KIT_OOPS_}
__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit] = ${__TB_TOUCH_FILE_DIR}/qbar_block^xl_vip_hvl_sysv_open_kit
__TB_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit] = ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]}
__TB_QAFENE_DEPS[uvc_qclk_dpi] += ${__TB_QAFENE_REQUIRES[uvc_qclk_dpi]}
__TB_SPEC_FILES[uvc_qclk_dpi] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/DPI/compile.xml
__TB_FILELISTS[uvc_qclk_dpi] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_qclk_dpi_hier_tb_systemc.f
__TB_SOURCE_FILES[uvc_qclk_dpi] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/DPI/qclk_proxy_dpi.cpp
__TB_SOURCE_FILES[uvc_qclk_dpi][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/DPI/qclk_proxy_dpi.cpp
__TB_FILELISTS[uvc_qclk_dpi][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_qclk_dpi_hier_tb_systemc.f
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${UVC_QCLK_DPI_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += $${UVC_QCLK_DPI_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${UVC_QCLK_DPI_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${__TB_SOURCE_FILES[uvc_qclk_dpi][1]}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${__TB_OPTS_FILES[uvc_qclk_dpi]}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[uvc_qclk_dpi][1]}),)
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${__TB_QAFENE_REQUIRES[uvc_qclk_dpi]}
__TB_QAFENE_DEPS[uvc_qclk_dpi][1] += ${__TB_CHECK_FILES[uvc_qclk_dpi]}
__TB_QAFENE_OOPS[uvc_qclk_dpi][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_qclk_dpi][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_qclk_dpi][1] += ${UVC_QCLK_DPI_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi][1] += $${UVC_QCLK_DPI_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi][1] += ${UVC_QCLK_DPI_OOPS_}
__HVL_QAFENE_TARGET[uvc_qclk_dpi][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_qclk_dpi.1
__TB_QAFENE_DEPS[uvc_qclk_dpi] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk_dpi] += ${UVC_QCLK_DPI_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi] += $${UVC_QCLK_DPI_DEPS}
__TB_QAFENE_DEPS[uvc_qclk_dpi] += ${UVC_QCLK_DPI_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk_dpi] += ${__HVL_QAFENE_TARGET[uvc_qclk_dpi][1]}
__TB_QAFENE_OOPS[uvc_qclk_dpi] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_qclk_dpi] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_qclk_dpi] += ${UVC_QCLK_DPI_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi] += $${UVC_QCLK_DPI_OOPS}
__TB_QAFENE_OOPS[uvc_qclk_dpi] += ${UVC_QCLK_DPI_OOPS_}
__HVL_QAFENE_TARGET[uvc_qclk_dpi] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_qclk_dpi
__TB_QAFENE_TARGET[uvc_qclk_dpi] = ${__HVL_QAFENE_TARGET[uvc_qclk_dpi]}
__TB_QAFENE_REQUIRES[uvc_qclk] += ${__HVL_QAFENE_TARGET[uvm]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_qclk] += ${__HVL_QAFENE_TARGET[quvm_addons]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_qclk] += ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_qclk] += ${__HVL_QAFENE_TARGET[uvc_qclk_dpi]${__TB_IGNORE_DEPS}}
__TB_QAFENE_DEPS[uvc_qclk] += ${__TB_QAFENE_REQUIRES[uvc_qclk]}
__TB_SPEC_FILES[uvc_qclk] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/compile.xml
__TB_FILELISTS[uvc_qclk] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_qclk_hier_tb_sv.f
__TB_SOURCE_FILES[uvc_qclk] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/qclk_pkg.sv
__TB_SOURCE_FILES[uvc_qclk][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/qclk_pkg.sv
__TB_FILELISTS[uvc_qclk][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_qclk_hier_tb_sv.f
__TB_QAFENE_DEPS[uvc_qclk][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk][1] += ${UVC_QCLK_DEPS}
__TB_QAFENE_DEPS[uvc_qclk][1] += $${UVC_QCLK_DEPS}
__TB_QAFENE_DEPS[uvc_qclk][1] += ${UVC_QCLK_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk][1] += ${__TB_SOURCE_FILES[uvc_qclk][1]}
__TB_QAFENE_DEPS[uvc_qclk][1] += ${__TB_OPTS_FILES[uvc_qclk]}
__TB_QAFENE_DEPS[uvc_qclk][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[uvc_qclk][1]}),)
__TB_QAFENE_DEPS[uvc_qclk][1] += ${__TB_QAFENE_REQUIRES[uvc_qclk]}
__TB_QAFENE_DEPS[uvc_qclk][1] += ${__TB_CHECK_FILES[uvc_qclk]}
__TB_QAFENE_OOPS[uvc_qclk][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_qclk][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_qclk][1] += ${UVC_QCLK_OOPS}
__TB_QAFENE_OOPS[uvc_qclk][1] += $${UVC_QCLK_OOPS}
__TB_QAFENE_OOPS[uvc_qclk][1] += ${UVC_QCLK_OOPS_}
__HVL_QAFENE_TARGET[uvc_qclk][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_qclk.1
__TB_QAFENE_DEPS[uvc_qclk] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_qclk] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk] += ${UVC_QCLK_DEPS}
__TB_QAFENE_DEPS[uvc_qclk] += $${UVC_QCLK_DEPS}
__TB_QAFENE_DEPS[uvc_qclk] += ${UVC_QCLK_DEPS_}
__TB_QAFENE_DEPS[uvc_qclk] += ${__HVL_QAFENE_TARGET[uvc_qclk][1]}
__TB_QAFENE_OOPS[uvc_qclk] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_qclk] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_qclk] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_qclk] += ${UVC_QCLK_OOPS}
__TB_QAFENE_OOPS[uvc_qclk] += $${UVC_QCLK_OOPS}
__TB_QAFENE_OOPS[uvc_qclk] += ${UVC_QCLK_OOPS_}
__HVL_QAFENE_TARGET[uvc_qclk] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_qclk
__TB_QAFENE_TARGET[uvc_qclk] = ${__HVL_QAFENE_TARGET[uvc_qclk]}
__TB_QAFENE_REQUIRES[uvc_pcounter] += ${__HVL_QAFENE_TARGET[uvm]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter] += ${__HVL_QAFENE_TARGET[quvm_addons]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter] += ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter] += ${__HVL_QAFENE_TARGET[uvc_qclk_dpi]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter] += ${__HVL_QAFENE_TARGET[uvc_qclk]${__TB_IGNORE_DEPS}}
__TB_QAFENE_DEPS[uvc_pcounter] += ${__TB_QAFENE_REQUIRES[uvc_pcounter]}
__TB_SPEC_FILES[uvc_pcounter] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/compile.xml
__TB_FILELISTS[uvc_pcounter] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_pcounter_hier_tb_sv.f
__TB_SOURCE_FILES[uvc_pcounter] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/pcounter_pkg.sv
__TB_SOURCE_FILES[uvc_pcounter][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/pcounter_pkg.sv
__TB_FILELISTS[uvc_pcounter][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_pcounter_hier_tb_sv.f
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${UVC_PCOUNTER_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter][1] += $${UVC_PCOUNTER_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${UVC_PCOUNTER_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${__TB_SOURCE_FILES[uvc_pcounter][1]}
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${__TB_OPTS_FILES[uvc_pcounter]}
__TB_QAFENE_DEPS[uvc_pcounter][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[uvc_pcounter][1]}),)
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${__TB_QAFENE_REQUIRES[uvc_pcounter]}
__TB_QAFENE_DEPS[uvc_pcounter][1] += ${__TB_CHECK_FILES[uvc_pcounter]}
__TB_QAFENE_OOPS[uvc_pcounter][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_pcounter][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_pcounter][1] += ${UVC_PCOUNTER_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter][1] += $${UVC_PCOUNTER_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter][1] += ${UVC_PCOUNTER_OOPS_}
__HVL_QAFENE_TARGET[uvc_pcounter][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_pcounter.1
__TB_QAFENE_DEPS[uvc_pcounter] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter] += ${UVC_PCOUNTER_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter] += $${UVC_PCOUNTER_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter] += ${UVC_PCOUNTER_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter] += ${__HVL_QAFENE_TARGET[uvc_pcounter][1]}
__TB_QAFENE_OOPS[uvc_pcounter] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_pcounter] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_pcounter] += ${UVC_PCOUNTER_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter] += $${UVC_PCOUNTER_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter] += ${UVC_PCOUNTER_OOPS_}
__HVL_QAFENE_TARGET[uvc_pcounter] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_pcounter
__TB_QAFENE_TARGET[uvc_pcounter] = ${__HVL_QAFENE_TARGET[uvc_pcounter]}
__TB_QAFENE_REQUIRES[uvc_pcounter_test] += ${__HVL_QAFENE_TARGET[uvm]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_test] += ${__HVL_QAFENE_TARGET[quvm_addons]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_test] += ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_test] += ${__HVL_QAFENE_TARGET[uvc_qclk_dpi]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_test] += ${__HVL_QAFENE_TARGET[uvc_qclk]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_test] += ${__HVL_QAFENE_TARGET[uvc_pcounter]${__TB_IGNORE_DEPS}}
__TB_QAFENE_DEPS[uvc_pcounter_test] += ${__TB_QAFENE_REQUIRES[uvc_pcounter_test]}
__TB_SPEC_FILES[uvc_pcounter_test] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/compile.xml
__TB_FILELISTS[uvc_pcounter_test] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_pcounter_test_hier_tb_sv.f
__TB_SOURCE_FILES[uvc_pcounter_test] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/pcounter_test_pkg.sv
__TB_SOURCE_FILES[uvc_pcounter_test][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/pcounter_test_pkg.sv
__TB_FILELISTS[uvc_pcounter_test][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_pcounter_test_hier_tb_sv.f
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${UVC_PCOUNTER_TEST_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += $${UVC_PCOUNTER_TEST_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${UVC_PCOUNTER_TEST_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${__TB_SOURCE_FILES[uvc_pcounter_test][1]}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${__TB_OPTS_FILES[uvc_pcounter_test]}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[uvc_pcounter_test][1]}),)
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${__TB_QAFENE_REQUIRES[uvc_pcounter_test]}
__TB_QAFENE_DEPS[uvc_pcounter_test][1] += ${__TB_CHECK_FILES[uvc_pcounter_test]}
__TB_QAFENE_OOPS[uvc_pcounter_test][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_pcounter_test][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_pcounter_test][1] += ${UVC_PCOUNTER_TEST_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test][1] += $${UVC_PCOUNTER_TEST_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test][1] += ${UVC_PCOUNTER_TEST_OOPS_}
__HVL_QAFENE_TARGET[uvc_pcounter_test][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_pcounter_test.1
__TB_QAFENE_DEPS[uvc_pcounter_test] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_test] += ${UVC_PCOUNTER_TEST_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test] += $${UVC_PCOUNTER_TEST_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_test] += ${UVC_PCOUNTER_TEST_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_test] += ${__HVL_QAFENE_TARGET[uvc_pcounter_test][1]}
__TB_QAFENE_OOPS[uvc_pcounter_test] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_pcounter_test] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_pcounter_test] += ${UVC_PCOUNTER_TEST_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test] += $${UVC_PCOUNTER_TEST_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_test] += ${UVC_PCOUNTER_TEST_OOPS_}
__HVL_QAFENE_TARGET[uvc_pcounter_test] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_pcounter_test
__TB_QAFENE_TARGET[uvc_pcounter_test] = ${__HVL_QAFENE_TARGET[uvc_pcounter_test]}
__TB_QAFENE_REQUIRES[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[uvm]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[quvm_addons]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[uvc_qclk_dpi]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[uvc_qclk]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[uvc_pcounter]${__TB_IGNORE_DEPS}}
__TB_QAFENE_REQUIRES[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[uvc_pcounter_test]${__TB_IGNORE_DEPS}}
__TB_QAFENE_DEPS[uvc_pcounter_tb] += ${__TB_QAFENE_REQUIRES[uvc_pcounter_tb]}
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/compile.xml
__TB_FILELISTS[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_pcounter_tb_hier_tb_sv.f
__TB_SOURCE_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/tb_top.sv
__TB_SOURCE_FILES[uvc_pcounter_tb][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/tb_top.sv
__TB_FILELISTS[uvc_pcounter_tb][1] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_pcounter_tb_hier_tb_sv.f
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${UVC_PCOUNTER_TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += $${UVC_PCOUNTER_TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${UVC_PCOUNTER_TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${__TB_SOURCE_FILES[uvc_pcounter_tb][1]}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${__TB_OPTS_FILES[uvc_pcounter_tb]}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += $(if ${__QBAR_CHECK_FILELIST_TIMESTAMPS},$(wildcard ${__TB_FILELISTS[uvc_pcounter_tb][1]}),)
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${__TB_QAFENE_REQUIRES[uvc_pcounter_tb]}
__TB_QAFENE_DEPS[uvc_pcounter_tb][1] += ${__TB_CHECK_FILES[uvc_pcounter_tb]}
__TB_QAFENE_OOPS[uvc_pcounter_tb][1] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_pcounter_tb][1] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb][1] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb][1] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_pcounter_tb][1] += ${UVC_PCOUNTER_TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb][1] += $${UVC_PCOUNTER_TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb][1] += ${UVC_PCOUNTER_TB_OOPS_}
__HVL_QAFENE_TARGET[uvc_pcounter_tb][1] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_pcounter_tb.1
__TB_QAFENE_DEPS[uvc_pcounter_tb] += ${__TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb] += $${TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb] += ${TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_tb] += ${UVC_PCOUNTER_TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb] += $${UVC_PCOUNTER_TB_DEPS}
__TB_QAFENE_DEPS[uvc_pcounter_tb] += ${UVC_PCOUNTER_TB_DEPS_}
__TB_QAFENE_DEPS[uvc_pcounter_tb] += ${__HVL_QAFENE_TARGET[uvc_pcounter_tb][1]}
__TB_QAFENE_OOPS[uvc_pcounter_tb] += ${__TB_INIT}
__TB_QAFENE_OOPS[uvc_pcounter_tb] += ${__TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb] += $${TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb] += ${TB_OOPS_}
__TB_QAFENE_OOPS[uvc_pcounter_tb] += ${UVC_PCOUNTER_TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb] += $${UVC_PCOUNTER_TB_OOPS}
__TB_QAFENE_OOPS[uvc_pcounter_tb] += ${UVC_PCOUNTER_TB_OOPS_}
__HVL_QAFENE_TARGET[uvc_pcounter_tb] = ${__TB_TOUCH_FILE_DIR}/qbar_block^uvc_pcounter_tb
__TB_QAFENE_TARGET[uvc_pcounter_tb] = ${__HVL_QAFENE_TARGET[uvc_pcounter_tb]}
__TB_MK_INCLUDED = ${true}
TB_DEPS?=
TB_DEPS_?=
__TB_LIBS += tb_work:${__TB_BIN_DIR}/tb_work
__TB_LIB_NAMES += tb_work
__TB_LIB_PATHS += ${__TB_BIN_DIR}/tb_work
__TB_VLOG_LIB_NAMES += tb_work
__SC_LIB_NAMES += tb_work
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/compile.xml
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/compile.xml
__TB_SPEC_FILES[uvc_pcounter_tb] += /prj/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/qcom_spec/hvl/sysv/compile_open_kit.xml
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/DPI/compile.xml
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/compile.xml
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/compile.xml
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/compile.xml
__TB_SPEC_FILES[uvc_pcounter_tb] += /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/compile.xml
__TB_SPEC_FILES += ${__TB_SPEC_FILES[uvc_pcounter_tb]}
__VLOG_OPTS += +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src
__SELF = /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/unmanaged/qvmr/xiaoshao/libs/default/tb/modelsim/6.6g/LINUX64/uvc_pcounter_tb_hier_tb.mk

.PHONY: ${__HVL_QAFENE_TARGET[uvm][1]} uvm ${__HVL_QAFENE_TARGET[uvm]} ${__HVL_QAFENE_TARGET[quvm_addons][1]} quvm_addons ${__HVL_QAFENE_TARGET[quvm_addons]} ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit][1]} xl_vip_hvl_sysv_open_kit ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]} ${__HVL_QAFENE_TARGET[uvc_qclk_dpi][1]} uvc_qclk_dpi ${__HVL_QAFENE_TARGET[uvc_qclk_dpi]} ${__HVL_QAFENE_TARGET[uvc_qclk][1]} uvc_qclk ${__HVL_QAFENE_TARGET[uvc_qclk]} ${__HVL_QAFENE_TARGET[uvc_pcounter][1]} uvc_pcounter ${__HVL_QAFENE_TARGET[uvc_pcounter]} ${__HVL_QAFENE_TARGET[uvc_pcounter_test][1]} uvc_pcounter_test ${__HVL_QAFENE_TARGET[uvc_pcounter_test]} ${__HVL_QAFENE_TARGET[uvc_pcounter_tb][1]} uvc_pcounter_tb ${__HVL_QAFENE_TARGET[uvc_pcounter_tb]}

################################################################################
#
# Command Definitions
#
################################################################################

ifneq (${TB_DONE},1)
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvm][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvm][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvm][1]} : \
	${__TB_QAFENE_DEPS[uvm][1]} | \
	${__TB_QAFENE_OOPS[uvm][1]}
	$(call __open_task,Compiling uvm for modelsim 1/1 (tb block 1 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[uvm][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__TB_VLOG_OPTS} ${TB_VLOG_OPTS} ${TB_VLOG_OPTS_} ${__UVM_VLOG_OPTS} ${UVM_VLOG_OPTS} ${UVM_VLOG_OPTS_} \
	    ${__TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS_} ${__UVM_SV_VLOG_OPTS} ${UVM_SV_VLOG_OPTS} ${UVM_SV_VLOG_OPTS_} \
	     \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/. \
	     `if [ -e ${__TB_BIN_DIR}//usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/uvm_pkg.sv.recompile ]; then echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/uvm_pkg.sv.recompile; else echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/release/src/uvm_pkg.sv; fi` \
	    -work tb_work \
	    ${__OVERRIDE_UVM_VLOG_OPTS} ${__UVM_VLOG_CMD_TRAIL} ${__UVM_VLOG_SV_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvm][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvm]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvm]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvm]} : \
	${__TB_QAFENE_DEPS[uvm]} | \
	${__TB_QAFENE_OOPS[uvm]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvm]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[uvm]},)

.SECONDEXPANSION:
uvm : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
uvm : \
	${__HVL_QAFENE_TARGET[uvm]} | 

$(eval __QAFENE_TARGET_DEFINED[uvm] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.uvm]},)

.SECONDEXPANSION:
clean_block.uvm : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.uvm :  | 
	$(call __open_task,Cleaning uvm for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[uvm]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.uvm] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[quvm_addons][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[quvm_addons][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[quvm_addons][1]} : \
	${__TB_QAFENE_DEPS[quvm_addons][1]} | \
	${__TB_QAFENE_OOPS[quvm_addons][1]}
	$(call __open_task,Compiling quvm_addons for modelsim 1/1 (tb block 2 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[quvm_addons][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__TB_VLOG_OPTS} ${TB_VLOG_OPTS} ${TB_VLOG_OPTS_} ${__QUVM_ADDONS_VLOG_OPTS} ${QUVM_ADDONS_VLOG_OPTS} ${QUVM_ADDONS_VLOG_OPTS_} \
	    ${__TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS_} ${__QUVM_ADDONS_SV_VLOG_OPTS} ${QUVM_ADDONS_SV_VLOG_OPTS} ${QUVM_ADDONS_SV_VLOG_OPTS_} \
	     \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/. \
	     `if [ -e ${__TB_BIN_DIR}//usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/quvm_addons_pkg.sv.recompile ]; then echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/quvm_addons_pkg.sv.recompile; else echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/quvm/addons/src/quvm_addons_pkg.sv; fi` \
	    -work tb_work \
	    ${__OVERRIDE_QUVM_ADDONS_VLOG_OPTS} ${__QUVM_ADDONS_VLOG_CMD_TRAIL} ${__QUVM_ADDONS_VLOG_SV_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[quvm_addons][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[quvm_addons]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[quvm_addons]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[quvm_addons]} : \
	${__TB_QAFENE_DEPS[quvm_addons]} | \
	${__TB_QAFENE_OOPS[quvm_addons]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[quvm_addons]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[quvm_addons]},)

.SECONDEXPANSION:
quvm_addons : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
quvm_addons : \
	${__HVL_QAFENE_TARGET[quvm_addons]} | 

$(eval __QAFENE_TARGET_DEFINED[quvm_addons] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.quvm_addons]},)

.SECONDEXPANSION:
clean_block.quvm_addons : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.quvm_addons :  | 
	$(call __open_task,Cleaning quvm_addons for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[quvm_addons]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.quvm_addons] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit][1]} : \
	${__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit][1]} | \
	${__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit][1]}
	$(call __open_task,Compiling xl_vip_hvl_sysv_open_kit for modelsim 1/1 (tb block 3 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[xl_vip_hvl_sysv_open_kit][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__TB_VLOG_OPTS} ${TB_VLOG_OPTS} ${TB_VLOG_OPTS_} ${__XL_VIP_HVL_SYSV_OPEN_KIT_VLOG_OPTS} ${XL_VIP_HVL_SYSV_OPEN_KIT_VLOG_OPTS} ${XL_VIP_HVL_SYSV_OPEN_KIT_VLOG_OPTS_} \
	    ${__TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS_} ${__XL_VIP_HVL_SYSV_OPEN_KIT_SV_VLOG_OPTS} ${XL_VIP_HVL_SYSV_OPEN_KIT_SV_VLOG_OPTS} ${XL_VIP_HVL_SYSV_OPEN_KIT_SV_VLOG_OPTS_} \
	     \
	    +incdir+${TBX_HOME}/questa/hdl \
	    +incdir+${TBX_HOME}/questa/hdl/xtlm \
	    +incdir+${XL_VIP_HOME}/xl_vip/lib \
	    -f `if [ -e ${__TB_BIN_DIR}/./xl_vip_hvl_sysv_open_kit_hier_tb_sv.f.recompile ]; then echo ./xl_vip_hvl_sysv_open_kit_hier_tb_sv.f.recompile; else echo ./xl_vip_hvl_sysv_open_kit_hier_tb_sv.f; fi` \
	    -work tb_work \
	    ${__OVERRIDE_XL_VIP_HVL_SYSV_OPEN_KIT_VLOG_OPTS} ${__XL_VIP_HVL_SYSV_OPEN_KIT_VLOG_CMD_TRAIL} ${__XL_VIP_HVL_SYSV_OPEN_KIT_VLOG_SV_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]} : \
	${__TB_QAFENE_DEPS[xl_vip_hvl_sysv_open_kit]} | \
	${__TB_QAFENE_OOPS[xl_vip_hvl_sysv_open_kit]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[xl_vip_hvl_sysv_open_kit]},)

.SECONDEXPANSION:
xl_vip_hvl_sysv_open_kit : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
xl_vip_hvl_sysv_open_kit : \
	${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]} | 

$(eval __QAFENE_TARGET_DEFINED[xl_vip_hvl_sysv_open_kit] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.xl_vip_hvl_sysv_open_kit]},)

.SECONDEXPANSION:
clean_block.xl_vip_hvl_sysv_open_kit : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.xl_vip_hvl_sysv_open_kit :  | 
	$(call __open_task,Cleaning xl_vip_hvl_sysv_open_kit for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[xl_vip_hvl_sysv_open_kit]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.xl_vip_hvl_sysv_open_kit] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk_dpi][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_qclk_dpi][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_qclk_dpi][1]} : \
	${__TB_QAFENE_DEPS[uvc_qclk_dpi][1]} | \
	${__TB_QAFENE_OOPS[uvc_qclk_dpi][1]}
	$(call __open_task,Compiling uvc_qclk_dpi for modelsim 1/1 (tb block 4 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[uvc_qclk_dpi][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__SCCOM}  \
	    ${__TB_SCCOM_OPTS} ${TB_SCCOM_OPTS} ${TB_SCCOM_OPTS_} ${__UVC_QCLK_DPI_SCCOM_OPTS} ${UVC_QCLK_DPI_SCCOM_OPTS} ${UVC_QCLK_DPI_SCCOM_OPTS_} \
	    ${__TB_SYSTEMC_SCCOM_OPTS} ${TB_SYSTEMC_SCCOM_OPTS} ${TB_SYSTEMC_SCCOM_OPTS_} ${__UVC_QCLK_DPI_SYSTEMC_SCCOM_OPTS} ${UVC_QCLK_DPI_SYSTEMC_SCCOM_OPTS} ${UVC_QCLK_DPI_SYSTEMC_SCCOM_OPTS_} \
	     \
	    -g \
	    -Wall \
	    -fPIC \
	    -DSC_INCLUDE_DYNAMIC_PROCESSES \
	    -I. \
	    -I/pkg/qct/software/modeltech/6.6g/include \
	    -I${XL_VIP_HOME}/xl_vip/lib \
	     `if [ -e ${__TB_BIN_DIR}//usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/DPI/qclk_proxy_dpi.cpp.recompile ]; then echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/DPI/qclk_proxy_dpi.cpp.recompile; else echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/DPI/qclk_proxy_dpi.cpp; fi` \
	    -work tb_work \
	    ${__OVERRIDE_UVC_QCLK_DPI_SCCOM_OPTS} ${__UVC_QCLK_DPI_SCCOM_CMD_TRAIL} ${__UVC_QCLK_DPI_SCCOM_SYSTEMC_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk_dpi][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk_dpi]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_qclk_dpi]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_qclk_dpi]} : \
	${__TB_QAFENE_DEPS[uvc_qclk_dpi]} | \
	${__TB_QAFENE_OOPS[uvc_qclk_dpi]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk_dpi]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[uvc_qclk_dpi]},)

.SECONDEXPANSION:
uvc_qclk_dpi : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
uvc_qclk_dpi : \
	${__HVL_QAFENE_TARGET[uvc_qclk_dpi]} | 

$(eval __QAFENE_TARGET_DEFINED[uvc_qclk_dpi] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.uvc_qclk_dpi]},)

.SECONDEXPANSION:
clean_block.uvc_qclk_dpi : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.uvc_qclk_dpi :  | 
	$(call __open_task,Cleaning uvc_qclk_dpi for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[uvc_qclk_dpi]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.uvc_qclk_dpi] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_qclk][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_qclk][1]} : \
	${__TB_QAFENE_DEPS[uvc_qclk][1]} | \
	${__TB_QAFENE_OOPS[uvc_qclk][1]}
	$(call __open_task,Compiling uvc_qclk for modelsim 1/1 (tb block 5 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[uvc_qclk][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__TB_VLOG_OPTS} ${TB_VLOG_OPTS} ${TB_VLOG_OPTS_} ${__UVC_QCLK_VLOG_OPTS} ${UVC_QCLK_VLOG_OPTS} ${UVC_QCLK_VLOG_OPTS_} \
	    ${__TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS_} ${__UVC_QCLK_SV_VLOG_OPTS} ${UVC_QCLK_SV_VLOG_OPTS} ${UVC_QCLK_SV_VLOG_OPTS_} \
	     \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/. \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/../sequence_lib/src \
	    +incdir+/usr/local/projects/qct/evals/veloce/software/iSolveTransactors/xl_vip2.4.0.2b/xl_vip/lib \
	     `if [ -e ${__TB_BIN_DIR}//usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/qclk_pkg.sv.recompile ]; then echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/qclk_pkg.sv.recompile; else echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/agents/qclk/env/src/qclk_pkg.sv; fi` \
	    -work tb_work \
	    ${__OVERRIDE_UVC_QCLK_VLOG_OPTS} ${__UVC_QCLK_VLOG_CMD_TRAIL} ${__UVC_QCLK_VLOG_SV_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_qclk]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_qclk]} : \
	${__TB_QAFENE_DEPS[uvc_qclk]} | \
	${__TB_QAFENE_OOPS[uvc_qclk]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_qclk]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[uvc_qclk]},)

.SECONDEXPANSION:
uvc_qclk : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
uvc_qclk : \
	${__HVL_QAFENE_TARGET[uvc_qclk]} | 

$(eval __QAFENE_TARGET_DEFINED[uvc_qclk] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.uvc_qclk]},)

.SECONDEXPANSION:
clean_block.uvc_qclk : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.uvc_qclk :  | 
	$(call __open_task,Cleaning uvc_qclk for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[uvc_qclk]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.uvc_qclk] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_pcounter][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_pcounter][1]} : \
	${__TB_QAFENE_DEPS[uvc_pcounter][1]} | \
	${__TB_QAFENE_OOPS[uvc_pcounter][1]}
	$(call __open_task,Compiling uvc_pcounter for modelsim 1/1 (tb block 6 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[uvc_pcounter][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__TB_VLOG_OPTS} ${TB_VLOG_OPTS} ${TB_VLOG_OPTS_} ${__UVC_PCOUNTER_VLOG_OPTS} ${UVC_PCOUNTER_VLOG_OPTS} ${UVC_PCOUNTER_VLOG_OPTS_} \
	    ${__TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS_} ${__UVC_PCOUNTER_SV_VLOG_OPTS} ${UVC_PCOUNTER_SV_VLOG_OPTS} ${UVC_PCOUNTER_SV_VLOG_OPTS_} \
	     \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/libs/verification/uvcs/qclk/env/src \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/. \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/../sequence_lib/src \
	     `if [ -e ${__TB_BIN_DIR}//usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/pcounter_pkg.sv.recompile ]; then echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/pcounter_pkg.sv.recompile; else echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/env/src/pcounter_pkg.sv; fi` \
	    -work tb_work \
	    ${__OVERRIDE_UVC_PCOUNTER_VLOG_OPTS} ${__UVC_PCOUNTER_VLOG_CMD_TRAIL} ${__UVC_PCOUNTER_VLOG_SV_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_pcounter]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_pcounter]} : \
	${__TB_QAFENE_DEPS[uvc_pcounter]} | \
	${__TB_QAFENE_OOPS[uvc_pcounter]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[uvc_pcounter]},)

.SECONDEXPANSION:
uvc_pcounter : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
uvc_pcounter : \
	${__HVL_QAFENE_TARGET[uvc_pcounter]} | 

$(eval __QAFENE_TARGET_DEFINED[uvc_pcounter] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.uvc_pcounter]},)

.SECONDEXPANSION:
clean_block.uvc_pcounter : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.uvc_pcounter :  | 
	$(call __open_task,Cleaning uvc_pcounter for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[uvc_pcounter]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.uvc_pcounter] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_test][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_pcounter_test][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_pcounter_test][1]} : \
	${__TB_QAFENE_DEPS[uvc_pcounter_test][1]} | \
	${__TB_QAFENE_OOPS[uvc_pcounter_test][1]}
	$(call __open_task,Compiling uvc_pcounter_test for modelsim 1/1 (tb block 7 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[uvc_pcounter_test][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__TB_VLOG_OPTS} ${TB_VLOG_OPTS} ${TB_VLOG_OPTS_} ${__UVC_PCOUNTER_TEST_VLOG_OPTS} ${UVC_PCOUNTER_TEST_VLOG_OPTS} ${UVC_PCOUNTER_TEST_VLOG_OPTS_} \
	    ${__TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS_} ${__UVC_PCOUNTER_TEST_SV_VLOG_OPTS} ${UVC_PCOUNTER_TEST_SV_VLOG_OPTS} ${UVC_PCOUNTER_TEST_SV_VLOG_OPTS_} \
	     \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/. \
	     `if [ -e ${__TB_BIN_DIR}//usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/pcounter_test_pkg.sv.recompile ]; then echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/pcounter_test_pkg.sv.recompile; else echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tests/src/pcounter_test_pkg.sv; fi` \
	    -work tb_work \
	    ${__OVERRIDE_UVC_PCOUNTER_TEST_VLOG_OPTS} ${__UVC_PCOUNTER_TEST_VLOG_CMD_TRAIL} ${__UVC_PCOUNTER_TEST_VLOG_SV_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_test][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_test]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_pcounter_test]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_pcounter_test]} : \
	${__TB_QAFENE_DEPS[uvc_pcounter_test]} | \
	${__TB_QAFENE_OOPS[uvc_pcounter_test]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_test]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[uvc_pcounter_test]},)

.SECONDEXPANSION:
uvc_pcounter_test : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
uvc_pcounter_test : \
	${__HVL_QAFENE_TARGET[uvc_pcounter_test]} | 

$(eval __QAFENE_TARGET_DEFINED[uvc_pcounter_test] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.uvc_pcounter_test]},)

.SECONDEXPANSION:
clean_block.uvc_pcounter_test : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.uvc_pcounter_test :  | 
	$(call __open_task,Cleaning uvc_pcounter_test for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[uvc_pcounter_test]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.uvc_pcounter_test] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_tb][1]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_pcounter_tb][1]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_pcounter_tb][1]} : \
	${__TB_QAFENE_DEPS[uvc_pcounter_tb][1]} | \
	${__TB_QAFENE_OOPS[uvc_pcounter_tb][1]}
	$(call __open_task,Compiling uvc_pcounter_tb for modelsim 1/1 (tb block 8 of 8),${__TB_INFO})
	-@$(call __quiet_rm,${__TB_FILELISTS[uvc_pcounter_tb][1]}.recompile,${__TB_LOG})
	$(call __locked_exec, \
	  ${__TB_BIN_DIR}/tb_work, \
	  ${CD} ${__TB_BIN_DIR} && \
	  ${__VLOG} -sv \
	    ${__TB_VLOG_OPTS} ${TB_VLOG_OPTS} ${TB_VLOG_OPTS_} ${__UVC_PCOUNTER_TB_VLOG_OPTS} ${UVC_PCOUNTER_TB_VLOG_OPTS} ${UVC_PCOUNTER_TB_VLOG_OPTS_} \
	    ${__TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS} ${TB_SV_VLOG_OPTS_} ${__UVC_PCOUNTER_TB_SV_VLOG_OPTS} ${UVC_PCOUNTER_TB_SV_VLOG_OPTS} ${UVC_PCOUNTER_TB_SV_VLOG_OPTS_} \
	     \
	    +incdir+/usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/. \
	     `if [ -e ${__TB_BIN_DIR}//usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/tb_top.sv.recompile ]; then echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/tb_top.sv.recompile; else echo /usr2/xiaoshao/uvm_training_labs/lab_backup/lab1/verif/sim/tb/src/tb_top.sv; fi` \
	    -work tb_work \
	    ${__OVERRIDE_UVC_PCOUNTER_TB_VLOG_OPTS} ${__UVC_PCOUNTER_TB_VLOG_CMD_TRAIL} ${__UVC_PCOUNTER_TB_VLOG_SV_CMD_TRAIL}, \
	  ${__TB_LOG}, \
	)
	$(call __dummy,$@,${__TB_LOG})
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_tb][1]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_tb]}]},)

.SECONDEXPANSION:
${__HVL_QAFENE_TARGET[uvc_pcounter_tb]} : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
${__HVL_QAFENE_TARGET[uvc_pcounter_tb]} : \
	${__TB_QAFENE_DEPS[uvc_pcounter_tb]} | \
	${__TB_QAFENE_OOPS[uvc_pcounter_tb]}
	$(call __dummy,$@,${__TB_LOG})

$(eval __QAFENE_TARGET_DEFINED[${__HVL_QAFENE_TARGET[uvc_pcounter_tb]}] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[uvc_pcounter_tb]},)

.SECONDEXPANSION:
uvc_pcounter_tb : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
uvc_pcounter_tb : \
	${__HVL_QAFENE_TARGET[uvc_pcounter_tb]} | 

$(eval __QAFENE_TARGET_DEFINED[uvc_pcounter_tb] := ${true})

endif
ifeq (${__QAFENE_TARGET_DEFINED[clean_block.uvc_pcounter_tb]},)

.SECONDEXPANSION:
clean_block.uvc_pcounter_tb : __CURRENT_LOG_FILE=${__TB_LOG_FILE}
clean_block.uvc_pcounter_tb :  | 
	$(call __open_task,Cleaning uvc_pcounter_tb for modelsim,${__TB_INFO})
	@$(call __quiet_rm, ${__HVL_QAFENE_TARGET[uvc_pcounter_tb]},)
	$(call __close_task,${__TB_INFO})

$(eval __QAFENE_TARGET_DEFINED[clean_block.uvc_pcounter_tb] := ${true})

endif
endif

